version: "3.5"
services:
  frontend:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    command: bash -c "cp -rf /workspace/* /app && dotnet dev-certs https && dotnet run --launch-profile Docker --project src/Trsys.Frontend.Web/Trsys.Frontend.Web.csproj"
    working_dir: /app
    volumes:
      - .:/workspace
    ports:
      - 5001:5001
      - 5000:5000
    environment:
      - Trsys__CopyTradingEndpoint=https://copy_trading:5003
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - copy_trading
  copy_trading:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    command: bash -c "cp -rf /workspace/* /app && dotnet dev-certs https && dotnet run --launch-profile Docker --project src/Trsys.CopyTrading.Service/Trsys.CopyTrading.Service.csproj"
    working_dir: /app
    volumes:
      - .:/workspace
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - JAVA_OPTS=-Xms256m -Xms256m -XX:+ExitOnOutOfMemoryError
    depends_on:
      - zipkin-storage
  zipkin-storage:
    image: openzipkin/zipkin-mysql
